### ISSUE TITLE
Open responsive menu covers logo/search?

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#10]
During the review of #8, @coreymckrill noticed [a bug in the layout](https://github.com/WordPress/wporg-mu-plugins/pull/8#pullrequestreview-768251199). I couldn't reproduce it, though, so opening an issue to gather more info. After the next sync to the staging site, we can check if others are seeing it, and try to figure out what's needed to trigger it.

> When the responsive mobile menu is open, it covers up the rest of the header where the WP icon and search button are.
> Additionally the X icon to close the menu has some weird padding.
> Maybe related to the mobile admin bar that gets pinned to the top when logged in?
Now the X close icon isn't even visible.

screenshot: https://user-images.githubusercontent.com/916023/135688737-4804252f-2ce5-49d1-9648-ddc96e75f3f8.png

**Comment by iandunn** [comment]
`div.wp-block-navigation__responsive-container.is-menu-open.has-modal-open` should have this CSS rule applied:

```css
body.admin-bar .site-header .wp-block-navigation__responsive-container.is-menu-open {
    top: calc(112px + var(--wp-admin--admin-bar--height));
}
```

Is that being overridden in your env, or just not showing up at all?
